import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, Download, FileUp, MapPin, Plus, Save, Trash2 } from 'lucide-react'
import { AlertBox, Button, Card, CardHeader } from '@/components/ui'
import { downloadJobFairResult, expressJobFairInterest, listEmployerJobFairs, respondToJobFairInvitation, submitJobFairConfirmation, submitJobFairResults, uploadJobFairRequirement } from '@/services/jobFairService'

const blankConfirmation = { representative_1_name: '', representative_1_contact: '', representative_2_name: '', representative_2_contact: '', email: '', number_of_job_vacancies: 0, will_conduct_onsite_interview: false, logistics_requests: '' }
const blankEntry = () => ({ applicant_name: '', gender: 'male', position_applied_for: '', status: 'near_hired', mismatch_code: '', remarks: '' })
const mismatchCodes = ['skills_mismatch', 'qualification_mismatch', 'experience_mismatch', 'education_mismatch', 'salary_expectation_mismatch', 'location_mismatch', 'availability_mismatch', 'incomplete_documents', 'failed_interview', 'other']

export default function EmployerJobFairDashboard() {
  const [fairs, setFairs] = useState([]); const [selectedId, setSelectedId] = useState(''); const [confirmation, setConfirmation] = useState(blankConfirmation); const [entries, setEntries] = useState([blankEntry()]); const [vacancies, setVacancies] = useState({ solicited: 0, offered: 0 }); const [remarks, setRemarks] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const selected = useMemo(() => fairs.find((x) => String(x.job_fair_id) === String(selectedId)) ?? fairs[0], [fairs, selectedId])
  const load = useCallback(async () => { setLoading(true); try { const data = await listEmployerJobFairs(); setFairs(data); if (!selectedId && data[0]) setSelectedId(String(data[0].job_fair_id)) } catch (e) { setError(e.response?.data?.message ?? 'Unable to load Job Fairs.') } finally { setLoading(false) } }, [selectedId])
  useEffect(() => { load() }, [load])
  const act = async (work, success) => { setError(''); setNotice(''); try { await work(); setNotice(success); await load() } catch (e) { setError(Object.values(e.response?.data?.errors ?? {}).flat().join(' ') || e.response?.data?.message || 'Action failed.') } }
  const updateEntry = (index, key, value) => setEntries((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value, ...(key === 'status' && value !== 'rejected' ? { mismatch_code: '' } : {}) } : row))
  const validEntries = entries.filter((e) => e.applicant_name && e.position_applied_for)
  const totals = { total_male: validEntries.filter((e) => e.gender === 'male').length, total_female: validEntries.filter((e) => e.gender === 'female').length, total_applicants: validEntries.length, total_hots: validEntries.filter((e) => e.status === 'hots').length, total_near_hired: validEntries.filter((e) => e.status === 'near_hired').length, total_rejected: validEntries.filter((e) => e.status === 'rejected').length }
  const download = async () => { try { const blob = await downloadJobFairResult(selected.participation.result_report.id); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `ro1-jf-form-3-${selected.job_fair_id}.pdf`; a.click(); URL.revokeObjectURL(url) } catch (e) { setError(e.response?.data?.message ?? 'Unable to generate report.') } }

  return <div className="portal-page">
    <div><p className="portal-eyebrow">Job Fair Ecosystem</p><h1 className="portal-title mt-1">Employer Coordination & Results</h1><p className="portal-subtitle">Complete digital steps when convenient. No laptop, QR scanner, or live system use is required at the venue.</p></div>
    {error && <AlertBox variant="danger" title="Job Fair action failed">{error}</AlertBox>}{notice && <AlertBox variant="success" title="Saved">{notice}</AlertBox>}
    <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-900"><strong>During the physical event:</strong> use your normal table, paper resumes, screening, and interview process. Return here afterward to encode results from your notes.</div>
    {loading ? <Card><p className="p-8 text-center">Loading announcements…</p></Card> : !fairs.length ? <Card><p className="p-8 text-center text-slate-500">No published Job Fairs are available.</p></Card> : <>
      <Card><CardHeader title="Job Fair announcement" subtitle="Select an event to view its coordination record." /><select value={selected?.job_fair_id ?? ''} onChange={(e) => setSelectedId(e.target.value)} className="w-full rounded-lg border p-3">{fairs.map((f) => <option key={f.job_fair_id} value={f.job_fair_id}>{f.title}</option>)}</select>
        <h2 className="mt-5 text-xl font-black">{selected?.title}</h2><p className="mt-2 text-sm text-slate-600">{selected?.description}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-slate-600"><span className="inline-flex gap-2"><CalendarDays className="h-4 w-4" />{selected?.start_date} · {selected?.start_time}–{selected?.end_time}</span><span className="inline-flex gap-2"><MapPin className="h-4 w-4" />{selected?.venue}</span></div>
        <div className="mt-4 flex flex-wrap gap-2">{!selected?.participation && <Button onClick={() => act(() => expressJobFairInterest(selected.job_fair_id), 'Interest sent to PESO.')}>Express Interest</Button>}{selected?.participation?.status === 'invited' && <><Button onClick={() => act(() => respondToJobFairInvitation(selected.job_fair_id, 'accepted'), 'Invitation accepted.')}>Accept Invitation</Button><Button variant="outline" onClick={() => act(() => respondToJobFairInvitation(selected.job_fair_id, 'declined'), 'Invitation declined.')}>Decline</Button></>}<a href={`mailto:${selected?.contact_email ?? ''}`} className="rounded-lg border px-4 py-2 text-sm font-bold">Contact PESO</a></div>
      </Card>
      {selected?.participation && <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader title="Event requirements" subtitle={`Participation status: ${selected.participation.status}`} /><div className="space-y-3">{selected.requirements.map((req) => { const submitted = selected.participation.requirements?.find((x) => x.job_fair_requirement_id === req.id); return <label key={req.id} className="block rounded-lg border p-3"><span className="text-sm font-bold">{req.label}</span><span className="ml-2 text-xs text-slate-500">{submitted?.status ?? 'pending'}</span>{req.code !== 'confirmation_slip' && <div className="mt-2 flex items-center gap-2"><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => e.target.files[0] && act(() => uploadJobFairRequirement(selected.job_fair_id, req.id, e.target.files[0]), `${req.label} submitted.`)} /><FileUp className="h-4 w-4 text-slate-400" /></div>}{submitted?.admin_remarks && <p className="mt-1 text-xs text-rose-700">PESO: {submitted.admin_remarks}</p>}</label>})}</div></Card>
        <Card><CardHeader title="Digital confirmation slip" subtitle={`Maximum ${selected.maximum_representatives} representatives.`} /><div className="grid gap-3 sm:grid-cols-2">{Object.entries(confirmation).map(([key, value]) => key === 'will_conduct_onsite_interview' ? <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value} onChange={(e) => setConfirmation((x) => ({ ...x, [key]: e.target.checked }))} />Will conduct on-site interview</label> : <label key={key} className="text-xs font-bold text-slate-600">{key.replaceAll('_', ' ')}<input type={key === 'number_of_job_vacancies' ? 'number' : key === 'email' ? 'email' : 'text'} value={value} onChange={(e) => setConfirmation((x) => ({ ...x, [key]: key === 'number_of_job_vacancies' ? Number(e.target.value) : e.target.value }))} className="mt-1 w-full rounded-lg border p-2" /></label>)}</div><Button className="mt-4" icon={Save} onClick={() => act(() => submitJobFairConfirmation(selected.job_fair_id, confirmation), 'Confirmation slip submitted.')}>Submit Confirmation</Button></Card>
      </div>}
      {selected?.participation && <Card><CardHeader title="Encode post-event results" subtitle="Enter applicants from your physical notes after the event." /><div className="space-y-3">{entries.map((entry, index) => <div key={index} className="grid gap-2 rounded-xl border bg-slate-50 p-3 md:grid-cols-6"><input value={entry.applicant_name} onChange={(e) => updateEntry(index, 'applicant_name', e.target.value)} placeholder="Applicant name" className="rounded-lg border p-2" /><select value={entry.gender} onChange={(e) => updateEntry(index, 'gender', e.target.value)} className="rounded-lg border p-2"><option value="male">Male</option><option value="female">Female</option></select><input value={entry.position_applied_for} onChange={(e) => updateEntry(index, 'position_applied_for', e.target.value)} placeholder="Position" className="rounded-lg border p-2" /><select value={entry.status} onChange={(e) => updateEntry(index, 'status', e.target.value)} className="rounded-lg border p-2"><option value="hots">HOTS</option><option value="near_hired">Near Hired</option><option value="rejected">Rejected</option></select><select disabled={entry.status !== 'rejected'} value={entry.mismatch_code} onChange={(e) => updateEntry(index, 'mismatch_code', e.target.value)} className="rounded-lg border p-2"><option value="">Mismatch reason</option>{mismatchCodes.map((code) => <option key={code} value={code}>{code.replaceAll('_', ' ')}</option>)}</select><Button variant="outline" icon={Trash2} onClick={() => setEntries((rows) => rows.filter((_, i) => i !== index))}>Remove</Button></div>)}</div><Button className="mt-3" variant="outline" icon={Plus} onClick={() => setEntries((rows) => [...rows, blankEntry()])}>Add Applicant</Button>
        <div className="mt-5 grid grid-cols-3 gap-3 md:grid-cols-6">{Object.entries(totals).map(([key, value]) => <div key={key} className="rounded-lg bg-slate-100 p-3"><p className="text-xl font-black">{value}</p><p className="text-[10px] font-bold text-slate-500">{key.replace('total_', '').replaceAll('_', ' ')}</p></div>)}</div>
        <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Vacancies solicited<input type="number" min="0" value={vacancies.solicited} onChange={(e) => setVacancies((x) => ({ ...x, solicited: Number(e.target.value) }))} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-xs font-bold">Vacancies offered<input type="number" min="0" value={vacancies.offered} onChange={(e) => setVacancies((x) => ({ ...x, offered: Number(e.target.value) }))} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-xs font-bold">Remarks<input value={remarks} onChange={(e) => setRemarks(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label></div>
        <div className="mt-4 flex gap-2"><Button icon={Save} disabled={!validEntries.length} onClick={() => act(() => submitJobFairResults(selected.job_fair_id, { ...totals, total_vacancies_solicited: vacancies.solicited, total_vacancies_offered: vacancies.offered, remarks, entries: validEntries.map((e) => ({ ...e, mismatch_code: e.mismatch_code || null })) }), 'Post-event results saved.')}>Save Results</Button>{selected.participation.result_report?.id && <Button variant="navy" icon={Download} onClick={download}>RO1-JF Form 3</Button>}</div>
      </Card>}
    </>}
  </div>
}
