<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 9px; line-height: 1.4; color: #111827; margin: 20px; }
    .center { text-align: center; }
    .header { margin-bottom: 16px; text-align: center; }
    h2, h3 { margin: 0; padding: 0; }
    h2 { font-size: 16px; margin-bottom: 5px; }
    h3 { font-size: 13px; font-weight: normal; color: #475569; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #cbd5e1; padding: 4px 5px; text-align: left; word-break: break-word; }
    th { background-color: #f8fafc; font-weight: bold; text-transform: uppercase; font-size: 8px; color: #475569; }
    .small { font-size: 9px; color: #64748b; margin-top: 16px; text-align: center; }
    .badge { border-radius: 4px; padding: 2px 4px; font-size: 9px; font-weight: bold; }
    .walk-in { background-color: #fef3c7; color: #92400e; }
    .registered { background-color: #dcfce7; color: #166534; }
    .letterhead { width: 100%; margin-bottom: 16px; border: none; }
    .letterhead td { border: none; vertical-align: middle; padding: 0; }
  </style>
</head>
<body>
  <table class="letterhead"><tr>
    <td style="width:52px"><img src="{{ public_path('images/urdaneta-city-seal.jpg') }}" alt="" style="width:52px"></td>
    <td class="center">
      <h2>Job Fair Attendance Report</h2>
      <h3>{{ $fair->title }} &middot; {{ optional($fair->start_date ?? $fair->event_date)->format('F d, Y') }}</h3>
      <h3>Total Checked-in: {{ count($rows) }}</h3>
    </td>
    <td style="width:52px;text-align:right"><img src="{{ public_path('images/peso-urdaneta-seal.jpg') }}" alt="" style="width:52px"></td>
  </tr></table>

  <table>
    <thead>
      <tr>
        <th style="width: 25px;">#</th>
        <th style="width: 55px;">Time In</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Contact Number</th>
        <th>Email</th>
        <th>Job Preference</th>
        <th>Preferred Work Location</th>
        <th>Language</th>
        <th>Education Attainment</th>
        <th>School/College/University</th>
        <th style="width: 45px;">Year Graduated/Last Attended</th>
        <th>Course</th>
        <th style="width: 50px;">Type</th>
      </tr>
    </thead>
    <tbody>
      @foreach($rows as $index => $row)
      <tr>
        <td>{{ $index + 1 }}</td>
        <td>{{ $row['time_in'] }}</td>
        <td style="font-weight: bold;">{{ $row['name'] }}</td>
        <td style="text-transform: capitalize;">{{ $row['gender'] }}</td>
        <td>{{ $row['contact_number'] }}</td>
        <td>{{ $row['email'] }}</td>
        <td>{{ $row['job_preference'] }}</td>
        <td>{{ $row['preferred_work_location'] }}</td>
        <td>{{ $row['language'] }}</td>
        <td>{{ $row['education_attainment'] }}</td>
        <td>{{ $row['school'] }}</td>
        <td>{{ $row['year_graduated'] }}</td>
        <td>{{ $row['course'] }}</td>
        <td>
          @if($row['type'] === 'Registered')
            <span class="badge registered">Registered</span>
          @else
            <span class="badge walk-in">Walk-in</span>
          @endif
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <p class="small">Generated by i-PESO at {{ now()->setTimezone('Asia/Manila')->format('M d, Y h:i A') }}. This report reflects job seekers checked in at the event's info desk.</p>
</body>
</html>
