<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; line-height: 1.4; color: #111827; margin: 30px; }
    .center { text-align: center; }
    .header { margin-bottom: 20px; text-align: center; }
    h2, h3 { margin: 0; padding: 0; }
    h2 { font-size: 16px; margin-bottom: 5px; }
    h3 { font-size: 13px; font-weight: normal; color: #475569; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
    th { background-color: #f8fafc; font-weight: bold; text-transform: uppercase; font-size: 10px; color: #475569; }
    .small { font-size: 9px; color: #64748b; margin-top: 20px; text-align: center; }
    .badge { border-radius: 4px; padding: 2px 4px; font-size: 9px; font-weight: bold; }
    .walk-in { background-color: #fef3c7; color: #92400e; }
    .registered { background-color: #dcfce7; color: #166534; }
  </style>
</head>
<body>
  <div class="header">
    <h2>Job Fair Attendance Report</h2>
    <h3>{{ $fair->title }} &middot; {{ optional($fair->start_date ?? $fair->event_date)->format('F d, Y') }}</h3>
    <h3>Total Checked-in: {{ $attendees->count() }}</h3>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width: 50px;">#</th>
        <th style="width: 100px;">Time In</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Contact Number</th>
        <th>Education</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      @foreach($attendees as $index => $att)
      @php
        $educ = $att->guest_educ_attainment ?? '-';
        if ($att->seeker && $att->seeker->educations->first()) {
            $educ = $att->seeker->educations->first()->education_level;
        }
      @endphp
      <tr>
        <td>{{ $index + 1 }}</td>
        <td>{{ $att->scanned_at ? $att->scanned_at->setTimezone('Asia/Manila')->format('h:i A') : '-' }}</td>
        <td style="font-weight: bold;">{{ $att->seeker ? trim($att->seeker->first_name . ' ' . $att->seeker->last_name) : $att->guest_name }}</td>
        <td style="text-transform: capitalize;">{{ $att->seeker ? ($att->seeker->sex ?? '-') : '-' }}</td>
        <td>{{ $att->seeker ? $att->seeker->mobile_number : $att->guest_mobile_number }}</td>
        <td>{{ $educ }}</td>
        <td>
          @if($att->seeker)
            <span class="badge registered">Registered</span>
          @else
            <span class="badge walk-in">Walk-in</span>
          @endif
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <p class="small">Generated by i-PESO at {{ now()->setTimezone('Asia/Manila')->format('M d, Y h:i A') }}. This report reflects job seekers checked in at the event's info desk.</p>
</body>
</html>
