<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:12px;line-height:1.65;color:#111827;margin:38px}.center{text-align:center}.date{text-align:right;margin:25px 0}.signature{margin-top:40px}.small{font-size:10px;color:#475569}</style></head><body>
<div class="center"><strong>PUBLIC EMPLOYMENT SERVICE OFFICE</strong><br>Urdaneta City, Pangasinan</div>
<div class="date">{{ now()->format('F d, Y') }}</div>
<p><strong>{{ $recipientName ?: ($employer?->representative_name ?: 'HR Manager') }}</strong><br>{{ $employer?->company_name ?: 'Prospective Participating Employer' }}</p>
<p>Dear Sir/Madam:</p>
<p>The Public Employment Service Office respectfully invites your company to participate in <strong>{{ $fair->title }}</strong>, scheduled on <strong>{{ optional($fair->start_date ?? $fair->event_date)->format('F d, Y') }}</strong>, from <strong>{{ date('g:i A', strtotime($fair->start_time)) }}</strong> to <strong>{{ date('g:i A', strtotime($fair->end_time)) }}</strong> at <strong>{{ $fair->venue }}</strong>.</p>
@if($fair->partner_agencies)<p>This activity is conducted in partnership with {{ collect($fair->partner_agencies)->join(', ', ' and ') }}.</p>@endif
<p>Please submit the following requirements by <strong>{{ optional($fair->submission_deadline)->format('F d, Y') ?: 'the announced deadline' }}</strong>:</p>
<ul>@foreach($fair->requirements()->orderBy('sort_order')->get() as $requirement)<li>{{ $requirement->label }}</li>@endforeach</ul>
<p>Please bring two printed copies of your job vacancy listings. Snacks and lunch will be provided for a maximum of <strong>{{ $fair->maximum_representatives ?? 2 }}</strong> company representatives.</p>
<p>For coordination, contact PESO at {{ $fair->contact_email ?: 'the PESO office' }}. Digital submission is available for convenience, while telephone, email, and in-person confirmation remain accepted.</p>
<p>We look forward to your participation.</p><div class="signature"><strong>PESO MANAGER</strong><br>Public Employment Service Office</div>
<p class="small">Generated by i-PESO. This invitation supports pre-event coordination and does not require digital equipment during the physical job fair.</p>
</body></html>
