<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin: 18px 0 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #9ca3af; padding: 8px; text-align: left; }
        th { background: #e5e7eb; }
        .muted { color: #4b5563; }
        .meta { margin-top: 6px; line-height: 1.5; }
    </style>
</head>
<body>
    <h1>DOLE SPRS Form 2018 - Section 1.6 Job Fair Report</h1>
    <div class="meta">
        <strong>Event:</strong> {{ $fair->title }}<br>
        <strong>Venue:</strong> {{ $fair->venue }}<br>
        <strong>Date:</strong> {{ optional($fair->start_date ?? $fair->event_date)->format('F d, Y') }}
        @if($fair->end_date && $fair->end_date->ne($fair->start_date ?? $fair->event_date))
            to {{ $fair->end_date->format('F d, Y') }}
        @endif
        <br>
        <strong>Sector:</strong> {{ ucfirst($fair->sector ?? 'local') }}
    </div>

    <h2>SPRS 1.6 Summary</h2>
    <table>
        <thead>
            <tr>
                <th>SPRS Line</th>
                <th>Indicator</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>1.6.1</td><td>Local Job Fairs Conducted</td><td>{{ $summary['1.6.1_fairs_conducted_local'] }}</td></tr>
            <tr><td>1.6.2</td><td>Overseas Job Fairs Conducted</td><td>{{ $summary['1.6.2_fairs_conducted_overseas'] }}</td></tr>
            <tr><td>1.6.3</td><td>Total Job Fairs Conducted</td><td>{{ $summary['1.6.3_total_fairs_conducted'] }}</td></tr>
            <tr><td>1.6.4</td><td>Establishments Participated</td><td>{{ $summary['1.6.4_establishments_participated'] }}</td></tr>
            <tr><td>1.6.5</td><td>Job Vacancies Solicited</td><td>{{ $summary['1.6.5_job_vacancies_solicited'] }}</td></tr>
            <tr><td>1.6.6</td><td>Job Applicants Registered</td><td>{{ $summary['1.6.6_job_applicants_registered'] }}</td></tr>
            <tr><td>1.6.7</td><td>Hired-On-The-Spot</td><td>{{ $summary['1.6.7_total_hots'] }}</td></tr>
        </tbody>
    </table>

    <p class="muted">Generated by i-PESO Digital Job Fair Module on {{ now()->format('F d, Y h:i A') }}.</p>
</body>
</html>
