<?php

return [
    'occupations' => [
        'Accountant',
        'Administrative Assistant',
        'Agricultural Technician',
        'Architect',
        'Automotive Mechanic',
        'Baker',
        'Bookkeeper',
        'Bus Driver',
        'Call Center Agent',
        'Carpenter',
        'Cashier',
        'Civil Engineer',
        'Computer Network Technician',
        'Computer Programmer',
        'Construction Laborer',
        'Cook',
        'Customer Service Representative',
        'Data Entry Operator',
        'Delivery Driver',
        'Domestic Cleaner',
        'Electrical Engineer',
        'Electrician',
        'Elementary School Teacher',
        'Food Service Counter Attendant',
        'Graphic Designer',
        'Heavy Truck Driver',
        'Hotel Receptionist',
        'Human Resource Officer',
        'Information Technology Support Technician',
        'Machine Operator',
        'Mason',
        'Mechanical Engineer',
        'Medical Technologist',
        'Nursing Assistant',
        'Office Clerk',
        'Pharmacist',
        'Plumber',
        'Production Supervisor',
        'Registered Nurse',
        'Restaurant Service Crew',
        'Retail Salesperson',
        'Security Guard',
        'Senior High School Teacher',
        'Software Developer',
        'Teacher Aide',
        'Tour Guide',
        'Warehouse Worker',
        'Web Developer',
        'Welder',
    ],
];
