<?php

return [
    'occupations' => [
        'Accountant',
        'Administrative Assistant',
        'Agricultural Technician',
        'Architect',
        'Automotive Mechanic',
        'Baker',
        'Bookkeeper',
        'Bus Driver',
        'Call Center Agent',
        'Carpenter',
        'Cashier',
        'Civil Engineer',
        'Computer Network Technician',
        'Computer Programmer',
        'Construction Laborer',
        'Cook',
        'Customer Service Representative',
        'Data Entry Operator',
        'Delivery Driver',
        'Domestic Cleaner',
        'Electrical Engineer',
        'Electrician',
        'Elementary School Teacher',
        'Food Service Counter Attendant',
        'Graphic Designer',
        'Heavy Truck Driver',
        'Hotel Receptionist',
        'Human Resource Officer',
        'Information Technology Support Technician',
        'Machine Operator',
        'Mason',
        'Mechanical Engineer',
        'Medical Technologist',
        'Nursing Assistant',
        'Office Clerk',
        'Pharmacist',
        'Plumber',
        'Production Supervisor',
        'Registered Nurse',
        'Restaurant Service Crew',
        'Retail Salesperson',
        'Security Guard',
        'Senior High School Teacher',
        'Software Developer',
        'Teacher Aide',
        'Tour Guide',
        'Warehouse Worker',
        'Web Developer',
        'Welder',
    ],

    'generalized_groups' => [
        ['term' => 'office work', 'label' => 'Office and Administration', 'keywords' => 'office admin clerical secretary receptionist encoder', 'patterns' => 'office clerk|administrative assistant|data entry|secretary|receptionist|records clerk'],
        ['term' => 'factory worker', 'label' => 'Manufacturing and Factory Work', 'keywords' => 'factory production machine operator assembler packer', 'patterns' => 'machine operator|production operator|production supervisor|assembler|packer|manufacturing|sewing machine'],
        ['term' => 'driver', 'label' => 'Driving and Transportation', 'keywords' => 'driver taxi jeepney bus truck transport', 'patterns' => 'driver|chauffeur|taxi|bus operator|jeepney|vehicle operator'],
        ['term' => 'delivery work', 'label' => 'Delivery and Courier Work', 'keywords' => 'delivery rider courier parcel messenger', 'patterns' => 'delivery|courier|messenger|parcel|rider'],
        ['term' => 'healthcare work', 'label' => 'Healthcare', 'keywords' => 'health nurse nursing midwife medical clinic hospital pharmacy', 'patterns' => 'nurse|midwife|physician|doctor|medical technologist|pharmacist|radiographer|health worker|dental'],
        ['term' => 'caregiver work', 'label' => 'Caregiving and Personal Care', 'keywords' => 'caregiver care aide elderly home care', 'patterns' => 'caregiver|care worker|care aide|nursing assistant|home care|personal care'],
        ['term' => 'construction work', 'label' => 'Construction', 'keywords' => 'construction laborer mason carpenter building', 'patterns' => 'construction|mason|carpenter|bricklayer|roofer|scaffolder|building worker'],
        ['term' => 'skilled trades', 'label' => 'Skilled Trades and Repair', 'keywords' => 'electrician plumber welder mechanic technician repair', 'patterns' => 'electrician|plumber|welder|mechanic|repair technician|aircon technician|refrigeration technician'],
        ['term' => 'hospitality work', 'label' => 'Hospitality and Hotels', 'keywords' => 'hotel hospitality room attendant front desk', 'patterns' => 'hotel|room attendant|housekeeping supervisor|accommodation|front desk'],
        ['term' => 'restaurant work', 'label' => 'Food Service and Restaurants', 'keywords' => 'restaurant food cook chef waiter service crew kitchen', 'patterns' => 'cook|chef|waiter|waitress|service crew|kitchen assistant|food service|restaurant'],
        ['term' => 'retail work', 'label' => 'Retail and Store Work', 'keywords' => 'retail store cashier salesperson sales merchandiser', 'patterns' => 'cashier|retail|shop assistant|salesperson|sales assistant|merchandiser|store keeper'],
        ['term' => 'agriculture work', 'label' => 'Agriculture and Farming', 'keywords' => 'farm farmer agriculture crop livestock poultry', 'patterns' => 'farmer|farm worker|agricultural|crop production|livestock|poultry|plantation'],
        ['term' => 'fishing work', 'label' => 'Fishing and Fish Processing', 'keywords' => 'fishing fisherman fishery fish processing aquaculture', 'patterns' => 'fishery|fisherman|fishing|fish processing|aquaculture'],
        ['term' => 'IT work', 'label' => 'IT and Computer Work', 'keywords' => 'IT computer programmer software web data technology network cybersecurity', 'patterns' => 'software|programmer|web developer|IT support|computer network|database|cybersecurity|systems analyst|data analyst'],
        ['term' => 'education work', 'label' => 'Education and Teaching', 'keywords' => 'teacher teaching education tutor school instructor trainer', 'patterns' => 'teacher|teaching assistant|teacher aide|tutor|school instructor|lecturer|education'],
        ['term' => 'logistics work', 'label' => 'Warehouse and Logistics', 'keywords' => 'warehouse logistics stock inventory forklift supply chain', 'patterns' => 'warehouse|forklift|inventory|stock clerk|supply chain|logistics'],
        ['term' => 'beauty work', 'label' => 'Beauty and Wellness', 'keywords' => 'beauty salon barber hairdresser massage nail makeup', 'patterns' => 'hairdresser|barber|manicurist|beautician|make-up artist|massage therapist|nail technician'],
        ['term' => 'household work', 'label' => 'Household and Domestic Services', 'keywords' => 'household domestic helper cleaner babysitter laundry kasambahay', 'patterns' => 'domestic|housekeeper|cleaner|babysitter|laundry worker|household helper'],
        ['term' => 'government work', 'label' => 'Government and Community Services', 'keywords' => 'government public service barangay community civil service', 'patterns' => 'government|civil registrar|public administration|barangay|community officer'],
        ['term' => 'BPO work', 'label' => 'BPO and Customer Service', 'keywords' => 'BPO call center customer service support agent contact center', 'patterns' => 'call centre|call center|customer service|contact centre|BPO|technical support representative'],
        ['term' => 'online work', 'label' => 'Online and Digital Work', 'keywords' => 'online remote virtual ecommerce content freelance virtual assistant', 'patterns' => 'virtual assistant|online seller|e-commerce|content creator|social media|remote work'],
        ['term' => 'finance work', 'label' => 'Accounting and Finance', 'keywords' => 'accounting finance accountant bookkeeper auditor tax payroll', 'patterns' => 'accountant|bookkeeper|auditor|accounting clerk|tax adviser|payroll'],
        ['term' => 'engineering work', 'label' => 'Engineering and Architecture', 'keywords' => 'engineering engineer architect architecture drafting', 'patterns' => 'engineer|architect|engineering technician|architectural drafter'],
        ['term' => 'security work', 'label' => 'Security and Protective Services', 'keywords' => 'security guard sekyu guwardiya protection police', 'patterns' => 'security guard|security officer|protective service|police officer|bodyguard'],
        ['term' => 'human resources work', 'label' => 'Human Resources and Recruitment', 'keywords' => 'human resources HR recruitment recruiter personnel talent payroll', 'patterns' => 'human resources|recruiter|recruitment|personnel officer|talent acquisition'],
        ['term' => 'legal work', 'label' => 'Legal and Compliance', 'keywords' => 'legal law lawyer attorney paralegal compliance court', 'patterns' => 'lawyer|attorney|paralegal|legal assistant|legal secretary|compliance officer'],
        ['term' => 'marketing work', 'label' => 'Marketing and Communications', 'keywords' => 'marketing advertising communications public relations brand promotion', 'patterns' => 'marketing|advertising|public relations|communications officer|brand manager'],
        ['term' => 'creative work', 'label' => 'Media Arts and Design', 'keywords' => 'creative media arts design graphic photo video writer', 'patterns' => 'graphic designer|artist|photographer|videographer|writer|editor|multimedia|animator'],
        ['term' => 'banking work', 'label' => 'Banking and Insurance', 'keywords' => 'bank banking insurance teller loan credit claims', 'patterns' => 'bank teller|bank account|bank manager|loan officer|insurance|credit officer|claims'],
        ['term' => 'real estate work', 'label' => 'Real Estate and Property Services', 'keywords' => 'real estate property broker leasing realtor', 'patterns' => 'real estate|property manager|leasing agent|property agent'],
        ['term' => 'science work', 'label' => 'Science, Research and Laboratory Work', 'keywords' => 'science scientist research laboratory lab biology chemistry', 'patterns' => 'scientist|researcher|laboratory|biologist|chemist|physicist'],
        ['term' => 'utilities work', 'label' => 'Utilities, Energy and Environment', 'keywords' => 'utilities energy power water environment waste renewable', 'patterns' => 'power plant|water treatment|waste management|environmental|renewable energy|utility worker'],
        ['term' => 'tourism work', 'label' => 'Tourism, Events and Recreation', 'keywords' => 'tourism tour travel events recreation leisure', 'patterns' => 'tour guide|travel consultant|event coordinator|event manager|recreation'],
        ['term' => 'social services work', 'label' => 'Social Services and Counseling', 'keywords' => 'social services social worker counselor counselling welfare', 'patterns' => 'social worker|counsellor|counselor|welfare worker|community development'],
        ['term' => 'management work', 'label' => 'Management and Business Operations', 'keywords' => 'management manager supervisor business operations entrepreneur', 'patterns' => 'general manager|operations manager|business manager|project manager|entrepreneur'],
    ],
];
