<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:8.5px;color:#111827}
h1{text-align:center;font-size:14px;margin:0}
.sub{text-align:center;margin:2px 0 10px;font-size:10px}
.muted{color:#475569}
table{width:100%;border-collapse:collapse;margin-top:8px}
th,td{border:1px solid #64748b;padding:3px 5px;vertical-align:top}
th{background:#e2e8f0;font-size:7.5px;text-transform:uppercase}
.num{text-align:center}
.sec{background:#cbd5e1;font-weight:bold;text-transform:uppercase}
.blank{color:#94a3b8}
.sign td{border:none;padding-top:26px;width:33%;text-align:center;font-size:9px}
.sign .line{border-top:1px solid #111827;padding-top:3px}
</style></head><body>
@php
  $v = fn($k, $d = null) => data_get($data, $k, $d);
  $rows = $data['rows'] ?? [];
  $cell = fn($value) => $value === null || $value === '' ? '<span class="blank">&nbsp;</span>' : e($value);
@endphp
<h1>STATISTICAL PERFORMANCE REPORTING SYSTEM (SPRS)</h1>
<div class="sub">PESO Monthly Operations Statistical Report &mdash; <strong>{{ $v('period', $report->title) }}</strong></div>

<table>
  <thead>
    <tr>
      <th rowspan="2" style="width:34%">Programs / Success Indicators</th>
      <th rowspan="2" style="width:7%">Whole Year Target</th>
      <th colspan="2">Previous Month<br>{{ $v('previous_period','') }}</th>
      <th colspan="2">Current Month<br>{{ $v('period','') }}</th>
      <th colspan="2">Cumulative (Jan&ndash;{{ $v('period','') }})</th>
    </tr>
    <tr>
      <th class="num">Total</th><th class="num">Female</th>
      <th class="num">Total</th><th class="num">Female</th>
      <th class="num">Total</th><th class="num">Female</th>
    </tr>
  </thead>
  <tbody>
    @if(empty($rows))
      <tr><td colspan="8" class="muted">This report was generated before the full-form layout was added. Regenerate it to see every indicator line.</td></tr>
    @endif
    @foreach($rows as $row)
      @if($row['section'] ?? false)
        <tr class="sec"><td colspan="8">{{ $row['label'] }}</td></tr>
      @else
        @php $pad = 8 + (($row['indent'] ?? 0) * 12); @endphp
        <tr>
          <td style="padding-left:{{ $pad }}px">{{ $row['label'] }}</td>
          <td class="num">{!! $cell($row['target'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['prev_total'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['prev_female'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['curr_total'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['curr_female'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['cum_total'] ?? null) !!}</td>
          <td class="num">{!! $cell($row['cum_female'] ?? null) !!}</td>
        </tr>
      @endif
    @endforeach
  </tbody>
</table>

<table style="margin-top:10px">
  <tbody>
    <tr class="sec"><td colspan="8">Other Accomplishments</td></tr>
    <tr>
      <td>First Time Jobseeker Act (RA 11261) <span class="muted">(Attachment Included: {!! $cell($v('other_accomplishments.ftja_with_attachment')) !!})</span></td>
      <td class="num">{!! $cell(null) !!}</td>
      <td class="num" colspan="2">{!! $cell($v('other_accomplishments.previous_ftja_total')) !!}</td>
      <td class="num" colspan="2">{!! $cell($v('other_accomplishments.ftja_total')) !!}</td>
      <td class="num" colspan="2">{!! $cell($v('other_accomplishments.cumulative_ftja_total')) !!}</td>
    </tr>
  </tbody>
</table>

<table style="margin-top:10px">
  <tbody>
    <tr class="sec"><td>Issues / Concerns</td></tr>
    <tr><td style="white-space:pre-wrap">{!! $cell($v('issues_concerns')) !!}</td></tr>
  </tbody>
</table>

<table class="sign"><tr>
  <td><div class="line">{{ data_get($signatories, 'prepared_by.name', '________________') }}<br><span class="muted">Prepared by{{ data_get($signatories,'prepared_by.position') ? ' — '.$signatories['prepared_by']['position'] : ' (SLEO/PESO Coordinator)' }}</span></div></td>
  <td><div class="line">{{ data_get($signatories, 'checked_by.name', '________________') }}<br><span class="muted">Checked by{{ data_get($signatories,'checked_by.position') ? ' — '.$signatories['checked_by']['position'] : ' (PESO Manager)' }}</span></div></td>
  <td><div class="line">{{ data_get($signatories, 'approved_by.name', '________________') }}<br><span class="muted">Approved by{{ data_get($signatories,'approved_by.position') ? ' — '.$signatories['approved_by']['position'] : ' (City Mayor)' }}</span></div></td>
</tr></table>

<p class="muted" style="margin-top:14px">Generated by i-PESO. Blank cells (shown grey) are not computed by the system and were left for manual encoding or correction before submission.</p>
</body></html>
